import {describe,it,expect,beforeEach,afterEach} from 'vitest'
import {LibraryDatabase} from '../packages/persistence/database'
import {querySchema} from '../packages/contracts'
let db:LibraryDatabase
const root={id:'root',name:'测试',path:'F:\\测试',entryId:'folder',identity:'volume:1:0'}
function entry(id:string,rel:string,kind='image',parentId='folder'){return {id,rootId:'root',parentId,kind,name:rel.split('/').pop()!,rel,ext:kind==='folder'?'':'jpg',size:100,mtime:1000,identity:'volume:'+id+':0',seen:'generation'}}
beforeEach(()=>{db=new LibraryDatabase(':memory:');db.addRoot(root)})
afterEach(()=>db.close())
describe('SQLite 索引与用户管理信息',()=>{
 it('分区、后代查询、短中文搜索与自然排序',()=>{db.ingest([entry('f','杭州','folder'),entry('a','图10.jpg'),entry('b','图2.jpg')]);db.ingest([entry('c','杭州/西湖.jpg','image','f')]);db.finishDirectory('folder','generation',2);db.finishScan('root');const direct=db.openQuery(querySchema.parse({folderId:'folder',scope:'direct'}));expect(direct.folders).toBe(1);expect(db.page(direct.id,0,20).entries.map(e=>e.name)).toEqual(['杭州','图2.jpg','图10.jpg']);const recursive=db.openQuery(querySchema.parse({folderId:'folder',scope:'descendants',text:'西湖'}));expect(db.page(recursive.id,0).entries.map(e=>e.id)).toEqual(['c']);expect(db.entry('folder').subtree).toBe(3);expect(db.entry('folder').other).toBe(2)})
 it('全选快照不纳入后续新增文件',()=>{db.ingest([entry('a','a.jpg')]);const q=db.openQuery(querySchema.parse({folderId:'folder',scope:'descendants'}));const snapshot=db.freeze(db.sessionIds(q.id));db.ingest([entry('b','b.jpg')]);db.organize({snapshotId:snapshot.snapshotId},'favorite',true);expect(db.entry('a').favorite).toBe(1);expect(db.entry('b').favorite).toBe(0)})
 it('外部同名替换不会错误继承旧收藏和标签',()=>{db.ingest([entry('a','same.jpg')]);db.organize({ids:['a']},'tag-add','旅行');db.organize({ids:['a']},'favorite',true);db.ingest([entry('new','same.jpg')]);expect(db.entry('a').state).toBe('replaced');expect(db.entry('new').favorite).toBe(0);expect(db.entry('new').tags).toEqual([])})
 it('手动封面抵挡迟到的自动任务与重扫',()=>{db.ingest([entry('a','a.jpg')]);expect(db.cover('a',0,{mode:'manual',hash:'manual',crop:{}},false)).toBe(1);expect(db.cover('a',0,{mode:'auto',hash:'automatic'},true)).toBe(0);db.ingest([{...entry('a','a.jpg'),size:200}]);expect(db.entry('a').coverHash).toBe('manual');expect(()=>db.cover('a',0,{mode:'manual',hash:'new'})).toThrow()})
 it('文件夹重命名更新后代路径、闭包、搜索但保留关联',()=>{db.ingest([entry('f','old','folder')]);db.ingest([entry('a','old/child.jpg','image','f')]);db.organize({ids:['a']},'tag-add','旅行');db.relocate('f','root','folder','new','new');expect(db.entry('a').rel).toBe('new/child.jpg');expect(db.entry('a').tags).toEqual(['旅行']);const q=db.openQuery(querySchema.parse({folderId:'folder',scope:'descendants',text:'new child'}));expect(q.media).toBe(1)})
 it('未完成扫描和离线不清除旧条目，完整目录才判定缺失',()=>{db.ingest([entry('a','a.jpg')]);db.rootState('root','offline');expect(db.entry('a').state).toBe('present');db.rootState('root','online');db.finishDirectory('folder','next-generation',0);expect(db.entry('a').state).toBe('missing')})
 it('多个标签为全部包含，路径字面通配符不扩展',()=>{db.ingest([entry('a','100%.jpg'),entry('b','other.jpg')]);db.organize({ids:['a','b']},'tag-add','旅行');db.organize({ids:['a']},'tag-add','杭州');const q=db.openQuery(querySchema.parse({folderId:null,scope:'library',tags:['旅行','杭州'],text:'%'}));expect(db.page(q.id,0).entries.map(e=>e.id)).toEqual(['a'])})
 it('自由搜索同时匹配标签、文件夹路径和文件名',()=>{db.ingest([entry('f','旅行素材','folder'),entry('a','旅行素材/sunset.mp4','video','f'),entry('b','portrait.jpg')]);db.organize({ids:['b']},'tag-add','人物精选');const byTag=db.openQuery(querySchema.parse({folderId:null,scope:'library',text:'人物'}));expect(db.page(byTag.id,0).entries.map(e=>e.id)).toEqual(['b']);const byFolder=db.openQuery(querySchema.parse({folderId:null,scope:'library',text:'旅行素材'}));expect(db.page(byFolder.id,0).entries.map(e=>e.id)).toEqual(['f','a']);const byName=db.openQuery(querySchema.parse({folderId:null,scope:'library',text:'sunset'}));expect(db.page(byName.id,0).entries.map(e=>e.id)).toEqual(['a'])})
 it('导入拒绝非法相对路径，并回滚事务',()=>{expect(()=>db.importRecords({roots:[{id:'other',name:'bad',entryId:'x'}],entries:[{...entry('x','../bad'),rootId:'other'}]})).toThrow();expect(db.allRoots()).toHaveLength(1)})
})
