import { useEffect,useState,type ReactNode,Component } from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import * as Dropdown from '@radix-ui/react-dropdown-menu'
import { X,Folder,Image as ImageIcon,Film,LoaderCircle,Check,Star,MoreHorizontal,Eye,Pin,Tag,Pencil,FolderInput,Trash2,Copy,ExternalLink,FolderOpen,ImagePlus } from 'lucide-react'
import type { Entry } from '../../../../packages/contracts'

export function IconButton({children,label,onClick,disabled=false,active=false}:{children:ReactNode;label:string;onClick?:()=>void;disabled?:boolean;active?:boolean}){return <button className={'icon-button'+(active?' active':'')} title={label} aria-label={label} onClick={onClick} disabled={disabled}>{children}</button>}
export function Modal({title,description,children,onClose,wide=false}:{title:string;description?:string;children:ReactNode;onClose:()=>void;wide?:boolean}){return <Dialog.Root open onOpenChange={open=>{if(!open)onClose()}}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className={'modal'+(wide?' wide':'')} aria-describedby={description?'modal-description':undefined}><header><div><Dialog.Title>{title}</Dialog.Title>{description&&<Dialog.Description id="modal-description">{description}</Dialog.Description>}</div><Dialog.Close asChild><button className="icon-button" aria-label="关闭"><X size={20}/></button></Dialog.Close></header>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
export function Thumb({entry,className=''}:{entry:Entry;className?:string}){const [url,setUrl]=useState('');const [error,setError]=useState('');useEffect(()=>{let active=true;let resource='';setUrl('');setError('');window.vm.media(entry.id,'thumbnail').then(value=>{resource=value;if(active)setUrl(value);else void window.vm.release(value)}).catch(e=>{if(active)setError(String(e))});return()=>{active=false;if(resource)void window.vm.release(resource)}},[entry.id,entry.revision,entry.coverRevision,entry.rootState]);return <div className={'thumbnail '+className} title={error||undefined}>{url?<img src={url} alt="" draggable={false} loading="lazy" onError={()=>{setError('缩略图不可用');setUrl('')}}/>:<div className={'placeholder '+entry.kind}>{entry.kind==='folder'?<Folder size={38} strokeWidth={1.2}/>:entry.kind==='video'?<Film size={30} strokeWidth={1.2}/>:<ImageIcon size={30} strokeWidth={1.2}/>}<span>{error?(entry.rootState==='offline'?'离线 · 缓存不可用':'暂无预览'):entry.kind==='folder'?'文件夹集合':'正在生成预览'}</span></div>}{entry.coverMode==='manual'&&<span className="cover-lock" title="手动封面已锁定"><Pin size={11}/></span>}</div>}
export function formatSize(value:number){if(value<1024)return value+' B';if(value<1024**2)return (value/1024).toFixed(1)+' KB';if(value<1024**3)return (value/1024**2).toFixed(1)+' MB';return (value/1024**3).toFixed(2)+' GB'}
export function formatTime(value:number|null){if(value==null)return '时长未知';const h=Math.floor(value/3600);const m=Math.floor(value/60)%60;const s=Math.floor(value)%60;return (h?h+':':'')+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
export function Busy({label='正在处理…'}:{label?:string}){return <div className="busy"><LoaderCircle size={20} className="spin"/>{label}</div>}
export type EntryAction='open'|'preview'|'favorite'|'tags'|'cover'|'locate'|'rename'|'move'|'trash'|'copy'|'reveal'|'external'
export function EntryMenu({entry,onAction,contextOpen=false,closeContext}:{entry:Entry;onAction:(action:EntryAction,entry:Entry)=>void;contextOpen?:boolean;closeContext?:()=>void}){const [open,setOpen]=useState(false);return <Dropdown.Root open={open||contextOpen} onOpenChange={value=>{setOpen(value);if(!value)closeContext?.()}}><Dropdown.Trigger asChild><button className="card-more icon-button" title="更多操作" aria-label={entry.name+' 的更多操作'} onClick={e=>e.stopPropagation()}><MoreHorizontal size={17}/></button></Dropdown.Trigger><Dropdown.Portal><Dropdown.Content className="context-menu" sideOffset={4} onClick={e=>e.stopPropagation()}>
 {([['open',entry.kind==='folder'?'进入文件夹':'打开',FolderOpen],['preview','快速预览',Eye],['favorite',entry.favorite?'取消收藏':'添加收藏',Star],['tags','编辑标签',Tag],...(entry.kind!=='image'?[['cover','设置封面',ImagePlus]]:[]),['locate','定位所在目录',Pin],['rename','重命名',Pencil],['move','移动到…',FolderInput],['trash','移入回收站',Trash2],['copy','复制路径',Copy],['reveal','在资源管理器中显示',Folder],['external','使用默认应用打开',ExternalLink]] as [EntryAction,string,typeof Folder][]).map(([action,label,Icon])=><Dropdown.Item key={action} className={action==='trash'?'danger-text':''} onSelect={()=>onAction(action,entry)}><Icon size={15}/>{label}</Dropdown.Item>)}
 </Dropdown.Content></Dropdown.Portal></Dropdown.Root>}
export function SelectionMark({selected}:{selected:boolean}){return <span className={'selection-mark'+(selected?' selected':'')} aria-hidden="true">{selected&&<Check size={12}/>}</span>}
export class ViewBoundary extends Component<{children:ReactNode;onReset:()=>void},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return {error:true}}render(){return this.state.error?<div className="empty-state"><h2>展示插件遇到问题</h2><p>浏览位置和媒体管理信息仍然保留。</p><button className="primary" onClick={()=>{this.props.onReset();this.setState({error:false})}}>恢复基础列表</button></div>:this.props.children}}
