import { useEffect,useRef,useState } from 'react'
import { ImagePlus,Film,ChevronLeft,ChevronRight,RefreshCw,Lock,Check,SlidersHorizontal } from 'lucide-react'
import type { Entry,Crop,Frame,CoverSource } from '../../../../packages/contracts'
import { Modal,Busy,formatTime,Thumb } from './components'
import { defaultQuery } from './store'

export function CoverEditor({target,initialTime=0,onClose,onSaved,notify}:{target:Entry;initialTime?:number;onClose:()=>void;onSaved:(entry:Entry)=>void;notify:(message:string)=>void}){
 const [destination,setDestination]=useState(target);const [source,setSource]=useState<CoverSource|null>(null);const [frame,setFrame]=useState<Frame|null>(null);const [time,setTime]=useState(initialTime);const [busy,setBusy]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [candidates,setCandidates]=useState<Frame[]>([]);const [entries,setEntries]=useState<Entry[]>([]);const [parent,setParent]=useState<Entry|null>(null)
 const [playing,setPlaying]=useState(false);const [snapshotStatus,setSnapshotStatus]=useState('');const playbackRef=useRef<HTMLVideoElement>(null)
 const [crop,setCrop]=useState<Crop>(()=>{try{return target.crop?JSON.parse(target.crop):{mode:'cover',x:.5,y:.5,zoom:1}}catch{return {mode:'cover',x:.5,y:.5,zoom:1}}});const generation=useRef(0);const sourceRef=useRef<CoverSource|null>(null);const mounted=useRef(true);const requested=useRef(false)
 const cropWidth=frame?Math.min(frame.width,frame.height*1.6)/crop.zoom:1;const cropHeight=cropWidth/1.6
 const previewStyle:React.CSSProperties=frame&&crop.mode==='cover'?{position:'absolute',width:`${frame.width/cropWidth*100}%`,height:`${frame.height/cropHeight*100}%`,left:`${-(frame.width/cropWidth*100-100)*crop.x}%`,top:`${-(frame.height/cropHeight*100-100)*crop.y}%`,maxWidth:'none',objectFit:'fill'}:{objectFit:'contain'}
 const seek=async(s:CoverSource,t:number,step=0)=>{const gen=++generation.current;setBusy(true);setError('');try{const result=await window.vm.frame(s.handle,t,step,gen);if(mounted.current&&gen===generation.current){setFrame(result);setTime(result.time)}}catch(e){if(gen===generation.current&&!String(e).includes('FRAME_SUPERSEDED'))setError(String(e))}finally{if(mounted.current&&gen===generation.current)setBusy(false)}}
 const choose=async(id:string|null)=>{setPlaying(false);setSnapshotStatus('');setBusy(true);setError('');try{const result=await window.vm.coverSource(id);if(result&&mounted.current){sourceRef.current=result;setSource(result);setFrame(null);await seek(result,id===target.id?initialTime:0)}}catch(e){setError(String(e))}finally{if(mounted.current)setBusy(false)}}
 const savedSnapshot=async()=>{setPlaying(false);setBusy(true);setError('');try{const result=await window.vm.coverSnapshot(target.id);setFrame(result.frame);setSource(null);setSnapshotStatus(result.status)}catch(e){setError(String(e))}finally{setBusy(false)}}
 const recommend=async()=>{setBusy(true);setError('');try{const result=await window.vm.recommend(target.id);setCandidates(result);if(!result.length)setError('没有可用候选，可选择本地图片或视频。')}catch(e){setError(String(e))}finally{setBusy(false)}}
 useEffect(()=>{mounted.current=true;if(!requested.current){requested.current=true;void window.vm.entry(target.id).then(setDestination);if(target.kind==='video')void choose(target.id);else if(target.coverMode==='manual'){void savedSnapshot();void recommend()}else void recommend();const folder=target.kind==='folder'?target.id:target.parentId;if(folder)void window.vm.openQuery({...defaultQuery,folderId:folder,scope:'descendants'}).then(q=>window.vm.page(q.id,0,200)).then(p=>{if(mounted.current)setEntries(p.entries)}).catch(()=>{});if(target.parentId)void window.vm.entry(target.parentId).then(setParent)}return()=>{mounted.current=false;if(sourceRef.current)void window.vm.closeSource(sourceRef.current.handle)}},[])
 const save=async()=>{if(!frame||busy)return;setSaving(true);try{const entry=await window.vm.saveCover(destination.id,frame.token,crop,destination.coverRevision);notify('封面已保存并锁定');onSaved(entry)}catch(e){setError(String(e));setSaving(false)}}
 return <Modal title="设置封面" description="保存独立图片快照，原始媒体不会被修改。" onClose={()=>{if(!saving)onClose()}} wide>
  <div className="cover-layout"><section className="cover-main"><div className="cover-preview" style={{aspectRatio:'16 / 10'}}>{playing&&source?.playbackUrl?<video ref={playbackRef} controls autoPlay src={source.playbackUrl} style={{width:'100%',height:'100%',objectFit:'contain'}} onLoadedMetadata={e=>{e.currentTarget.currentTime=time}} onPause={e=>{const t=e.currentTarget.currentTime;setPlaying(false);void seek(source,t)}} onError={()=>{setPlaying(false);setError('此编码不能播放定位，请使用时间轴直接选帧。')}}/>:frame?<img src={frame.url} alt="待保存的封面预览" style={previewStyle}/>:<div className="placeholder"><ImagePlus size={44}/><p>选择图片、视频或推荐候选</p></div>}{busy&&<div className="preview-wait"><Busy label="正在解码实际画面…"/></div>}<span className="ratio-label">16:10</span></div>
   {source?.kind==='video'&&<div className="frame-controls"><button className="secondary" disabled={busy||playing||!source.playbackUrl} onClick={()=>setPlaying(true)}><Film size={15}/>播放定位，暂停后选帧</button><input aria-label="视频时间轴" type="range" min="0" max={Math.max(.01,source.duration)} step="0.001" value={time} onChange={e=>setTime(Number(e.target.value))} onPointerUp={()=>void seek(source,time)} onKeyUp={e=>{if(e.key.startsWith('Arrow'))void seek(source,time)}}/><div><button className="secondary" disabled={busy} onClick={()=>void seek(source,time,-1)}><ChevronLeft size={16}/>前一帧</button><label>时间 <input type="number" aria-label="定位时间（秒）" min="0" step="0.001" max={source.duration} value={Number(time.toFixed(6))} onChange={e=>setTime(Number(e.target.value))}/><span>秒</span></label><button className="secondary" disabled={busy} onClick={()=>void seek(source,time)}>定位</button><button className="secondary" disabled={busy} onClick={()=>void seek(source,time,1)}>后一帧<ChevronRight size={16}/></button></div><small>实际画面时间 {frame?frame.time.toFixed(6):'—'} 秒 · 时长 {formatTime(source.duration)}</small></div>}
   {error&&<p className="inline-error" role="alert">{error}</p>}
   <div className="candidate-heading"><strong>推荐候选</strong><button className="text-button" disabled={busy} onClick={()=>void recommend()}><RefreshCw size={14}/>重新推荐</button></div><div className="candidates">{candidates.map(c=><button key={c.token} className={frame?.token===c.token?'selected':''} disabled={busy} onClick={()=>{setPlaying(false);setFrame(c);setTime(c.time);setSource(null);setSnapshotStatus('');setError('')}}><img src={c.url} alt={`候选画面 ${formatTime(c.time)}`}/>{frame?.token===c.token&&<Check size={16}/>}</button>)}{!candidates.length&&!busy&&<small>候选按画面清晰度、曝光等本地指标生成。</small>}</div>
  </section><aside className="cover-options"><label className="field"><span>封面用于</span><select value={destination.id} onChange={e=>{void window.vm.entry(e.target.value).then(setDestination)}}><option value={target.id}>{target.name}</option>{target.kind==='video'&&parent&&<option value={parent.id}>所在文件夹 · {parent.name}</option>}</select></label><div className="divider"/><h4><ImagePlus size={16}/>选择来源</h4><button className="secondary full-width" disabled={busy} onClick={()=>void choose(null)}>从本地选择图片或视频</button><select aria-label="当前目录媒体来源" value={source?.sourceId??''} disabled={busy} onChange={e=>{if(e.target.value)void choose(e.target.value)}}><option value="">当前目录及子目录中的媒体…</option>{entries.map(e=><option key={e.id} value={e.id}>{e.kind==='video'?'视频':'图片'} · {e.name}</option>)}</select><small>{snapshotStatus||source?.name||'快照独立保存，可随时更换来源'}</small>{target.coverMode==='manual'&&<button className="text-button" disabled={busy} onClick={()=>void savedSnapshot()}>编辑已保存快照</button>}<div className="divider"/><h4><SlidersHorizontal size={16}/>画面裁剪</h4><div className="segmented"><button className={crop.mode==='cover'?'selected':''} onClick={()=>setCrop({...crop,mode:'cover'})}>填满封面</button><button className={crop.mode==='contain'?'selected':''} onClick={()=>setCrop({...crop,mode:'contain'})}>完整显示</button></div><label className="field">缩放 <input type="range" aria-label="封面缩放" disabled={crop.mode==='contain'} min="1" max="4" step="0.01" value={crop.zoom} onChange={e=>setCrop({...crop,zoom:Number(e.target.value)})}/></label><label className="field">水平位置<input type="range" aria-label="封面水平位置" min="0" max="1" step="0.01" value={crop.x} onChange={e=>setCrop({...crop,x:Number(e.target.value)})}/></label><label className="field">垂直位置<input type="range" aria-label="封面垂直位置" min="0" max="1" step="0.01" value={crop.y} onChange={e=>setCrop({...crop,y:Number(e.target.value)})}/></label><p className="cover-note"><Lock size={15}/>手动封面会锁定，扫描和自动推荐不会覆盖。</p></aside></div>
  <footer className="modal-footer"><button className="text-button" disabled={busy||saving} onClick={async()=>{if(destination.coverMode==='manual'&&!window.confirm('恢复自动封面会替换当前手动设置，继续吗？'))return;setBusy(true);try{const entry=await window.vm.restoreCover(destination.id,destination.coverRevision);notify('已恢复自动封面');onSaved(entry)}catch(e){setError(String(e));setBusy(false)}}}>恢复自动封面</button><div><button className="secondary" onClick={onClose} disabled={saving}>取消</button><button className="primary" disabled={!frame||busy||saving||playing||!!(source&&frame.generation!==generation.current)} onClick={()=>void save()}><Check size={16}/>{saving?'正在保存…':'保存封面'}</button></div></footer>
 </Modal>
}
