import {useEffect,useRef,useState,type CSSProperties} from 'react'
import {Pause,Play,Maximize,Minimize,Volume2,ImagePlus,RefreshCw,ExternalLink,ChevronLeft,ChevronRight,MapPin,Subtitles,AudioLines} from 'lucide-react'
import type {Entry,MpvAction,MpvState,MpvBounds} from '../../../../packages/contracts'
import {Busy,formatTime,IconButton} from './components'

export function MpvPlayback({entry,onCover,onLocate,notify,onMove,previous,next}:{entry:Entry;onCover:(entry:Entry,time:number)=>void;onLocate:(entry:Entry)=>void;notify:(message:string)=>void;onMove:(direction:number)=>void;previous:boolean;next:boolean}){
 const [state,setState]=useState<MpvState|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[fullscreen,setFullscreen]=useState(false),[seeking,setSeeking]=useState<number|null>(null),[controlsVisible,setControlsVisible]=useState(true)
 const session=useRef(''),surface=useRef<HTMLDivElement>(null),container=useRef<HTMLDivElement>(null)
 const idleTimer=useRef<ReturnType<typeof setTimeout>|null>(null),dragging=useRef(false),seekSequence=useRef(0),lastPointer=useRef({x:-1,y:-1}),pointerHandler=useRef<(x:number,y:number)=>void>(()=>{})
 const clearIdle=()=>{if(idleTimer.current)clearTimeout(idleTimer.current);idleTimer.current=null}
 const armIdle=()=>{clearIdle();idleTimer.current=setTimeout(()=>{if(dragging.current){armIdle();return}setControlsVisible(false)},2000)}
 pointerHandler.current=(x,y)=>{if(!fullscreen)return;if(lastPointer.current.x===x&&lastPointer.current.y===y)return;lastPointer.current={x,y};const rect=container.current?.getBoundingClientRect();if(!rect||x<rect.left||x>rect.right||y<rect.top||y>rect.bottom)return;if(y>=rect.bottom-120){setControlsVisible(true);armIdle()}else if(controlsVisible)armIdle()}
 useEffect(()=>{clearIdle();setControlsVisible(!fullscreen);lastPointer.current={x:-1,y:-1};return clearIdle},[fullscreen])
 const getBounds=():MpvBounds=>{const rect=surface.current?.getBoundingClientRect(),scale=window.devicePixelRatio;return rect?{x:Math.max(0,Math.round(rect.x*scale)),y:Math.max(0,Math.round(rect.y*scale)),width:Math.max(0,Math.round(rect.width*scale)),height:Math.max(0,Math.round(rect.height*scale))}:{x:0,y:0,width:0,height:0}}
 useEffect(()=>{
  let active=true,opened='',animation=0,lastBounds='',updating=false;session.current='';setState(null);setError('');setSeeking(null)
  const unsubscribe=window.vm.onEvent(event=>{if(event.topic==='mpv-pointer'){const point=event.data as {sessionId:string;x:number;y:number};if(active&&point.sessionId===session.current)pointerHandler.current(point.x/window.devicePixelRatio,point.y/window.devicePixelRatio)}if(event.topic==='mpv-state'){const value=event.data as MpvState;if(active&&value.sessionId===session.current)setState(value)}})
  const updateBounds=()=>{if(!active)return;const bounds=getBounds(),key=JSON.stringify(bounds);if(opened&&!updating&&key!==lastBounds){updating=true;void window.vm.mpvBounds(opened,bounds).then(()=>{lastBounds=key}).catch(()=>{}).finally(()=>{updating=false})}animation=requestAnimationFrame(updateBounds)}
  void window.vm.startMpv(entry.id,getBounds()).then(value=>{opened=value.sessionId;if(active){session.current=opened;setState(value);animation=requestAnimationFrame(updateBounds)}else void window.vm.closeMpv(opened).catch(()=>{})}).catch(reason=>{if(active)setError(String(reason))})
  return()=>{active=false;cancelAnimationFrame(animation);unsubscribe();if(opened){void window.vm.mpvBounds(opened,{x:0,y:0,width:0,height:0}).catch(()=>{});void window.vm.closeMpv(opened).catch(()=>{})}}
 },[entry.id,attempt])
 const control=async(action:MpvAction,value?:number)=>{if(!session.current)return;try{await window.vm.mpvControl(session.current,action,value)}catch(error){notify(String(error))}}
 const full=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else {setControlsVisible(false);await container.current?.requestFullscreen()}}catch(error){notify(String(error))}}
 useEffect(()=>{const changed=()=>setFullscreen(document.fullscreenElement===container.current);document.addEventListener('fullscreenchange',changed);return()=>document.removeEventListener('fullscreenchange',changed)},[])
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Tab'&&document.fullscreenElement===container.current){setControlsVisible(true);armIdle()}if((event.target as HTMLElement).matches('input,select,textarea,button,[role=slider]'))return;if(event.code==='Space'){event.preventDefault();void control('toggle-pause')}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[])
 const ready=state?.status==='ready',failure=error||state?.error
 const cover=async()=>{if(!state)return;try{await window.vm.mpvBounds(state.sessionId,{x:0,y:0,width:0,height:0});await window.vm.closeMpv(state.sessionId);if(document.fullscreenElement)await document.exitFullscreen();onCover(entry,state.position)}catch(error){notify(String(error))}}
 const commitSeek=async(value:number)=>{const sequence=++seekSequence.current;setSeeking(value);try{await window.vm.mpvControl(session.current,'seek',value)}catch(error){notify(String(error))}finally{if(sequence===seekSequence.current)setSeeking(null)}}
 const duration=state?.duration??0,position=seeking??state?.position??0
 const targetAt=(element:HTMLDivElement,x:number)=>{const rect=element.getBoundingClientRect();return Math.max(0,Math.min(1,(x-rect.left)/Math.max(1,rect.width)))*duration}
 const aspect=state?.aspect||(entry.width&&entry.height?entry.width/entry.height:16/9)

 return <section className="mpv-viewer" ref={container} style={{'--mpv-aspect':aspect} as CSSProperties} onPointerMove={event=>pointerHandler.current(event.clientX,event.clientY)}>
  <div className="viewer-stage mpv-stage">
   <div className="mpv-surface" ref={surface} onDoubleClick={()=>void full()}/>
   {!state&&!error&&<Busy label="正在打开视频…"/>}
   {(failure||state?.status==='closed')&&<div className="viewer-error"><p>{failure||'播放已结束'}</p><div className="button-row"><button className="secondary" onClick={()=>setAttempt(value=>value+1)}><RefreshCw size={16}/>重新播放</button><button className="secondary" onClick={()=>void window.vm.system(entry.id,'open').catch(error=>notify(String(error)))}><ExternalLink size={16}/>系统默认应用</button></div></div>}
  </div>
  <div className="mpv-controls-panel" hidden={fullscreen&&!controlsVisible} onPointerUp={()=>{dragging.current=false;if(fullscreen)armIdle()}} onPointerCancel={()=>{dragging.current=false;if(fullscreen)armIdle()}}>
  <div className="mpv-seek"><span>{formatTime(position)}</span><div className="mpv-seek-track" role="slider" aria-label="mpv 播放进度" aria-valuemin={0} aria-valuemax={duration} aria-valuenow={Math.min(position,duration)} aria-valuetext={`${position.toFixed(2)} 秒`} aria-disabled={!ready||!duration} tabIndex={ready&&duration?0:-1} onPointerDown={event=>{if(!ready||!duration||event.button!==0)return;event.preventDefault();dragging.current=true;event.currentTarget.setPointerCapture(event.pointerId);setSeeking(targetAt(event.currentTarget,event.clientX))}} onPointerMove={event=>{if(event.currentTarget.hasPointerCapture(event.pointerId))setSeeking(targetAt(event.currentTarget,event.clientX))}} onPointerUp={event=>{if(!event.currentTarget.hasPointerCapture(event.pointerId))return;const value=targetAt(event.currentTarget,event.clientX);event.currentTarget.releasePointerCapture(event.pointerId);dragging.current=false;void commitSeek(value)}} onPointerCancel={()=>{dragging.current=false;setSeeking(null)}} onKeyDown={event=>{if(!ready||!duration)return;let value=position;if(['ArrowRight','ArrowUp'].includes(event.key))value+=5;else if(['ArrowLeft','ArrowDown'].includes(event.key))value-=5;else if(event.key==='Home')value=0;else if(event.key==='End')value=duration;else return;event.preventDefault();event.stopPropagation();void commitSeek(Math.max(0,Math.min(duration,value)));if(fullscreen)armIdle()}}><span className="mpv-seek-fill" style={{width:`${duration?Math.min(100,position/duration*100):0}%`}}/><span className="mpv-seek-thumb" style={{left:`${duration?Math.min(100,position/duration*100):0}%`}}/></div><span>{formatTime(duration)}</span></div>
  <footer className="viewer-tools mpv-tools"><div><IconButton label="上一项" disabled={!previous} onClick={()=>onMove(-1)}><ChevronLeft size={18}/></IconButton><IconButton label="下一项" disabled={!next} onClick={()=>onMove(1)}><ChevronRight size={18}/></IconButton><IconButton label={state?.paused?'播放':'暂停'} disabled={!ready} onClick={()=>void control('toggle-pause')}>{state?.paused?<Play size={18}/>:<Pause size={18}/>}</IconButton><select aria-label="播放速度" disabled={!ready} value={state?.speed??1} onChange={event=>void control('speed',Number(event.target.value))}>{[.5,.75,1,1.25,1.5,2,3,4].map(rate=><option key={rate} value={rate}>{rate}×</option>)}</select><label className="mpv-volume"><Volume2 size={17}/><input aria-label="mpv 音量" type="range" min="0" max="100" disabled={!ready} value={state?.volume??100} onChange={event=>void control('volume',Number(event.target.value))}/></label><IconButton label="切换音轨" disabled={!ready} onClick={()=>void control('audio')}><AudioLines size={17}/></IconButton><IconButton label="切换字幕" disabled={!ready} onClick={()=>void control('subtitle')}><Subtitles size={17}/></IconButton><button className="secondary" disabled={!ready} onClick={()=>void cover()}><ImagePlus size={16}/>设为封面</button></div><div><span className="badge">mpv</span><button className="text-button" onClick={()=>onLocate(entry)}><MapPin size={16}/>定位所在目录</button><IconButton label={fullscreen?'退出全屏':'全屏'} onClick={()=>void full()}>{fullscreen?<Minimize size={18}/>:<Maximize size={18}/>}</IconButton></div></footer>
 </div>
 </section>
}
