import { useCallback,useEffect,useRef,useState } from 'react'
import { ChevronLeft,ChevronRight,Minus,Plus,RotateCw,Maximize,Minimize,Expand,ImagePlus,MapPin,ExternalLink,Pause,Play } from 'lucide-react'
import {MpvPlayback} from './MpvPlayback'
import type { Entry,QuerySession,VideoPlayer } from '../../../../packages/contracts'
import { Modal,IconButton,Busy,formatTime } from './components'

export function Viewer({initial,session,ordinal,player='chromium',onClose,onLocate,onCover,notify}:{initial:Entry;session:QuerySession;ordinal:number;player?:VideoPlayer;onClose:()=>void;onLocate:(entry:Entry)=>void;onCover:(entry:Entry,time:number)=>void;notify:(message:string)=>void}){
 const [entry,setEntry]=useState(initial);const [index,setIndex]=useState(ordinal);const [url,setUrl]=useState('');const [error,setError]=useState('');const [zoom,setZoom]=useState(0);const [rotation,setRotation]=useState(0);const [pan,setPan]=useState({x:0,y:0});const [rate,setRate]=useState('1');const [position,setPosition]=useState(0);const [playing,setPlaying]=useState(false);const [fullscreen,setFullscreen]=useState(false)
 const external=entry.kind==='video'&&player!=='chromium'
 const video=useRef<HTMLVideoElement>(null);const stage=useRef<HTMLDivElement>(null);const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);const lastSave=useRef(0)
 useEffect(()=>{let active=true;let resource='';setUrl('');setError('');setZoom(0);setRotation(0);setPan({x:0,y:0});setPosition(0);setPlaying(false);if(external){if(player==='system')void window.vm.system(entry.id,'open').catch(e=>{if(active)setError(String(e))});return()=>{active=false}}window.vm.media(entry.id,'original').then(value=>{resource=value;if(active)setUrl(value);else void window.vm.release(value)}).catch(e=>{if(active)setError(String(e))});const element=video.current;return()=>{active=false;if(element){void window.vm.playback(entry.id,element.currentTime).catch(()=>{});element.pause();element.removeAttribute('src');element.load()}if(resource)void window.vm.release(resource)}},[entry.id,player])
 const move=useCallback(async(direction:number)=>{const next=index+direction;if(next<session.folders||next>=session.total)return;try{const page=await window.vm.page(session.id,next,1);const e=page.entries[0];if(e){setEntry(e);setIndex(next)}}catch(e){notify(String(e))}},[index,session,notify])
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(entry.kind==='video'&&player==='mpv')return;if((e.target as HTMLElement).matches('input,select,textarea,[role=slider]'))return;if(e.key==='ArrowLeft'){e.preventDefault();void move(-1)}if(e.key==='ArrowRight'){e.preventDefault();void move(1)}if(e.code==='Space'&&video.current){e.preventDefault();if(video.current.paused)void video.current.play().catch(e=>setError(String(e)));else video.current.pause()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[move,entry.kind,player])
 useEffect(()=>{const changed=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',changed);return()=>document.removeEventListener('fullscreenchange',changed)},[])
 const full=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(stage.current)await stage.current.requestFullscreen({navigationUI:'hide'})}catch(e){notify('无法进入全屏：'+(e instanceof Error?e.message:String(e)))}}
 if(entry.kind==='video'&&player==='mpv')return <Modal title={entry.name} description={`${index-session.folders+1} / ${session.media}　·　${entry.rel}`} onClose={onClose} wide><MpvPlayback key={entry.id} entry={entry} onCover={onCover} onLocate={onLocate} notify={notify} onMove={direction=>void move(direction)} previous={index>session.folders} next={index<session.total-1}/></Modal>
 return <Modal title={entry.name} description={`${index-session.folders+1} / ${session.media}　·　${entry.rel}`} onClose={onClose} wide>
  <div className="viewer-stage" ref={stage} onDoubleClick={()=>{if(!external)void full()}} onPointerDown={e=>{if(entry.kind==='image'&&zoom>0){drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};e.currentTarget.setPointerCapture(e.pointerId)}}} onPointerMove={e=>{if(drag.current)setPan({x:drag.current.px+e.clientX-drag.current.x,y:drag.current.py+e.clientY-drag.current.y})}} onPointerUp={()=>{drag.current=null}} onWheel={e=>{if(entry.kind==='image')setZoom(z=>Math.max(.1,Math.min(5,(z||1)+(e.deltaY<0?.1:-.1))))}}>
   {external&&(<div className="external-player-state"><ExternalLink size={36}/><h3>{error||'已交给系统默认应用播放'}</h3><p>播放控制和进度由外部播放器管理。</p><button className="secondary" onClick={()=>void window.vm.system(entry.id,'open').catch(e=>setError(String(e)))}>再次打开</button></div>)}
   {!external&&!url&&!error&&<Busy label="正在打开媒体…"/>}
   {!external&&(error?<div className="viewer-error"><p>无法在内置查看器中打开此媒体</p><small>{error}</small><button className="secondary" onClick={()=>void window.vm.system(entry.id,'open').catch(e=>notify(String(e)))}><ExternalLink size={16}/>使用系统默认应用打开</button></div>:url&&(entry.kind==='image'?<img className={zoom?'viewer-image original':'viewer-image fit'} src={url} alt={entry.name} draggable={false} style={{transform:`translate(${pan.x}px,${pan.y}px) rotate(${rotation}deg) scale(${zoom||1})`}} onError={()=>setError('图片格式不受支持或文件已损坏')}/>:<video key={entry.id} ref={video} src={url} controls preload="metadata" onError={()=>setError('当前容器中的视频／音频编码无法播放，可尝试系统默认应用')} onLoadedMetadata={e=>{const v=e.currentTarget;if(entry.playback>0&&entry.playback<v.duration-2)v.currentTime=entry.playback;v.playbackRate=Number(rate)}} onTimeUpdate={e=>{setPosition(e.currentTarget.currentTime);if(Date.now()-lastSave.current>5000){lastSave.current=Date.now();void window.vm.playback(entry.id,e.currentTarget.currentTime)}}} onPlay={()=>setPlaying(true)} onPause={e=>{setPlaying(false);void window.vm.playback(entry.id,e.currentTarget.currentTime)}}/>))}
   <button className="viewer-arrow prev" aria-label="上一项" disabled={index<=session.folders} onClick={()=>void move(-1)}><ChevronLeft size={26}/></button><button className="viewer-arrow next" aria-label="下一项" disabled={index>=session.total-1} onClick={()=>void move(1)}><ChevronRight size={26}/></button>
   {fullscreen&&<button className="viewer-exit-fullscreen" aria-label="退出全屏" onClick={()=>void full()}><Minimize size={19}/>退出全屏</button>}
  </div>
  <footer className="viewer-tools"><div>{entry.kind==='image'?<><IconButton label="缩小" onClick={()=>setZoom(z=>Math.max(.1,(z||1)-.25))}><Minus size={18}/></IconButton><button className="text-button" onClick={()=>setZoom(1)}>{zoom?Math.round(zoom*100)+'%':'适应窗口'}</button><IconButton label="放大" onClick={()=>setZoom(z=>Math.min(5,(z||1)+.25))}><Plus size={18}/></IconButton><IconButton label="适应窗口" onClick={()=>{setZoom(0);setPan({x:0,y:0})}}><Expand size={18}/></IconButton><IconButton label="临时旋转" onClick={()=>setRotation(r=>r+90)}><RotateCw size={18}/></IconButton></>:!external?<><IconButton label={playing?'暂停':'播放'} onClick={()=>{if(video.current?.paused)void video.current.play().catch(e=>setError(String(e)));else video.current?.pause()}}>{playing?<Pause size={18}/>:<Play size={18}/>}</IconButton><span className="mono">{formatTime(position)}</span><select aria-label="播放速度" value={rate} onChange={e=>{setRate(e.target.value);if(video.current)video.current.playbackRate=Number(e.target.value)}}>{['0.5','0.75','1','1.25','1.5','2'].map(v=><option key={v} value={v}>{v}×</option>)}</select><button className="secondary" onClick={()=>{video.current?.pause();onCover(entry,video.current?.currentTime??0)}}><ImagePlus size={16}/>设为封面</button></>:<span className="badge">{player==='mpv'?'mpv 播放器':'系统默认应用'}</span>}</div><div><button className="text-button" onClick={()=>onLocate(entry)}><MapPin size={16}/>定位所在目录</button>{!external&&<IconButton label={fullscreen?'退出全屏':'全屏'} onClick={()=>void full()}>{fullscreen?<Minimize size={18}/>:<Maximize size={18}/>}</IconButton>}</div></footer>
 </Modal>
}
