import {_electron as electron} from 'playwright'
import fs from 'node:fs/promises'
import path from 'node:path'
import assert from 'node:assert/strict'
import {randomUUID,createHash} from 'node:crypto'
const destinationBase=process.env.VM_CROSS_VOLUME_ROOT
if(!destinationBase)throw Error('VM_CROSS_VOLUME_ROOT must point to an explicitly permitted test directory on another volume')
const id=randomUUID(),base=path.resolve('.test-data/cross-'+id),source=path.join(base,'source'),destination=path.join(destinationBase,'cross-'+id),data=path.join(base,'app')
await fs.mkdir(path.join(source,'整目录','深层'),{recursive:true});await fs.mkdir(destination,{recursive:true})
await fs.writeFile(path.join(source,'整目录','深层','frame.jpg'),Buffer.alloc(5*1024**2,43));await fs.writeFile(path.join(source,'整目录','notes.txt'),'non-media must move too');await fs.writeFile(path.join(source,'keep-source.jpg'),Buffer.alloc(3*1024**2,61));await fs.writeFile(path.join(source,'cancel.jpg'),Buffer.alloc(64*1024**2,127))
const application=await electron.launch({executablePath:path.resolve('node_modules/electron/dist/electron.exe'),args:['.'],env:{...process.env,VM_DATA_DIR:data,VM_TEST_ROOT:source,VM_TEST_HIDDEN:'1'},timeout:30000});const page=await application.firstWindow();await page.waitForFunction(()=>!!window.vm);const results=[]
const api=(method,...args)=>page.evaluate(([method,args])=>window.vm[method](...args),[method,args]);const poll=async fn=>{for(let i=0;i<400;i++){const v=await fn();if(v)return v;await new Promise(r=>setTimeout(r,150))}throw Error('timeout')};const finished=id=>poll(async()=>{const b=await api('bootstrap');return b.tasks.find(t=>t.id===id&&!['running','paused'].includes(t.state))});const log=name=>{results.push({name,passed:true});console.log('PASS',name)}
try{
 const first=await poll(async()=>{const b=await api('bootstrap');return b.roots[0]?.state==='online'?b:null});const root=first.roots[0]
 await application.evaluate(({dialog},destination)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[destination]})},destination);const picked=await api('pickRoot');const target=await api('addRoot',picked.grant);await poll(async()=>{const b=await api('bootstrap');return b.roots.every(r=>r.state==='online')})
 const q=await api('openQuery',{folderId:root.entryId,scope:'direct'}),entries=(await api('page',q.id,0,100)).entries;const directory=entries.find(e=>e.name==='整目录');await api('organize',{ids:[directory.id]},'tag-add','整目录标签');const oldChildren=await api('children',directory.id);const innerQuery=await api('openQuery',{folderId:directory.id,scope:'descendants'});const media=(await api('page',innerQuery.id,0,100)).entries[0];await api('organize',{ids:[media.id]},'favorite',true)
 const plan=await api('plan',{ids:[directory.id]},'move',target.entryId,null,'skip');assert.equal(plan.items[0].files,2);await api('commit',plan.id);const result=await finished(plan.id);assert.equal(result.state,'completed',JSON.stringify(result));assert.equal(await fs.readFile(path.join(destination,'整目录','notes.txt'),'utf8'),'non-media must move too');await assert.rejects(fs.stat(path.join(source,'整目录')));const moved=await api('entry',directory.id);assert.equal(moved.rootId,target.id);assert.deepEqual(moved.tags,['整目录标签']);assert.equal((await api('entry',media.id)).favorite,1);assert.equal((await api('entry',media.id)).rootId,target.id);log('跨物理卷目录移动保留全部内容、目录 ID 与后代收藏')
 const kept=entries.find(e=>e.name==='keep-source.jpg');await fs.chmod(path.join(source,kept.name),0o444);await api('refreshRoot',root.id);await poll(async()=>{const b=await api('bootstrap');return b.roots.find(r=>r.id===root.id)?.state==='online'});const keepPlan=await api('plan',{ids:[kept.id]},'move',target.entryId,null,'skip');await api('commit',keepPlan.id);const keepResult=await finished(keepPlan.id);assert.equal(keepResult.state,'completed-errors');const a=await fs.readFile(path.join(source,kept.name)),b=await fs.readFile(path.join(destination,kept.name));assert.equal(createHash('sha256').update(a).digest('hex'),createHash('sha256').update(b).digest('hex'));assert.equal((await api('entry',kept.id)).rootId,root.id);await fs.chmod(path.join(source,kept.name),0o666);log('复制成功但源删除失败：两处完整保留，原条目关联不变')
 const cancelled=entries.find(e=>e.name==='cancel.jpg');const cancelPlan=await api('plan',{ids:[cancelled.id]},'move',target.entryId,null,'skip');await api('commit',cancelPlan.id);await api('taskAction',cancelPlan.id,'cancel');const cancelResult=await finished(cancelPlan.id);assert.equal(cancelResult.state,'cancelled');assert.equal((await fs.stat(path.join(source,cancelled.name))).size,64*1024**2);log('跨盘任务取消保留源文件')
}catch(error){console.error(error);results.push({name:'cross volume failure',passed:false,error:String(error)});process.exitCode=1}finally{await application.close();await fs.writeFile('test-results/cross-volume.json',JSON.stringify({source,destination,results},null,2))}
