import {_electron as electron} from 'playwright'
import fs from 'node:fs/promises'
import path from 'node:path'
import assert from 'node:assert/strict'
import {spawnSync} from 'node:child_process'
const base=path.resolve('.test-data/extra-'+Date.now()),source=path.join(base,'媒体'),data=path.join(base,'data');await fs.mkdir(base,{recursive:true});await fs.cp('.test-data/fixtures',source,{recursive:true})
const results=[];let application,page
const log=name=>{results.push({name,passed:true});console.log('PASS',name)}
const api=(method,...args)=>page.evaluate(([method,args])=>window.vm[method](...args),[method,args])
async function until(fn){const start=Date.now();while(Date.now()-start<30000){if(await fn())return;await new Promise(r=>setTimeout(r,150))}throw Error('Timed out')}
async function launch(){application=await electron.launch({executablePath:path.resolve(process.env.VM_TEST_EXECUTABLE||'node_modules/electron/dist/electron.exe'),args:process.env.VM_TEST_EXECUTABLE?[]:['.'],env:{...process.env,VM_DATA_DIR:data,VM_TEST_HIDDEN:'1'}});page=await application.firstWindow();await page.waitForFunction(()=>!!window.vm);await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].showInactive())}
try{
 await launch();await application.evaluate(({dialog},source)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[source]})},source);const picked=await api('pickRoot');const root=await api('addRoot',picked.grant);await until(async()=>{const b=await api('bootstrap');return b.tasks.some(t=>t.kind==='scan'&&t.state==='completed')});await page.locator('.tree-target').filter({hasText:'媒体'}).first().click()
 const q=await api('openQuery',{folderId:root.entryId,scope:'direct'});const entries=(await api('page',q.id,0,100)).entries;const folder=entries.find(e=>e.kind==='folder'),picture=entries.find(e=>e.ext==='jpg'),video=entries.find(e=>e.ext==='mp4'&&e.size>1000)
 await page.locator('.viewport [role=option]').first().click({button:'right'});await page.getByRole('menuitem',{name:'设置封面',exact:true}).waitFor();await page.keyboard.press('Escape');log('右键菜单显示文件操作入口')
 const opened=await api('coverSource',picture.id);const frame=await api('frame',opened.handle,0,0,1);const fresh=await api('entry',folder.id);await api('saveCover',folder.id,frame.token,{mode:'cover',x:.5,y:.5,zoom:1},fresh.coverRevision);await api('closeSource',opened.handle);const saved=await api('entry',folder.id)
 await fs.rename(path.join(source,picture.rel),path.join(base,picture.name));await api('refreshRoot',root.id);await until(async()=>{const e=await api('entry',picture.id);return e.state==='missing'});const snap=await api('coverSnapshot',folder.id);assert(snap.status.includes('来源已不可用'));const target=await api('entry',folder.id);await api('saveCover',folder.id,snap.frame.token,{mode:'cover',x:.2,y:.6,zoom:1.5},target.coverRevision);assert.equal((await api('entry',folder.id)).coverOriginal,saved.coverOriginal);log('来源移出后独立快照仍可显示和再次裁剪')
 await page.getByRole('textbox',{name:'搜索文件名、文件夹或标签'}).fill(video.name);await until(()=>page.locator('.viewport [role=option]').count().then(n=>n===1));await page.getByRole('button',{name:video.name+' 的更多操作',exact:true}).click();await page.getByRole('menuitem',{name:'设置封面',exact:true}).click();const play=page.getByRole('button',{name:'播放定位，暂停后选帧',exact:true});await until(()=>play.isEnabled());await play.click();await page.waitForFunction(()=>document.querySelector('.cover-preview video')?.currentTime>.1);await page.locator('.cover-preview video').evaluate(v=>v.pause());await until(()=>page.getByRole('button',{name:'保存封面',exact:true}).isEnabled());await page.getByRole('button',{name:'取消',exact:true}).last().click();log('封面编辑器播放暂停后获得实际解码帧')
 const codecFile=path.join(base,'VP8-Vorbis.webm');const encoded=spawnSync(process.env.VM_TEST_FFMPEG||'D:\\LosslessCut-win-x64\\resources\\ffmpeg.exe',['-hide_banner','-loglevel','error','-y','-f','lavfi','-i','testsrc2=size=320x240:rate=24:duration=2','-f','lavfi','-i','sine=duration=2','-c:v','libvpx','-c:a','libvorbis',codecFile],{windowsHide:true,encoding:'utf8'});assert.equal(encoded.status,0,encoded.stderr);await application.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]})},codecFile);const codec=await api('coverSource',null);const info=await page.evaluate(async url=>{const v=document.createElement('video');v.muted=true;v.src=url;document.body.append(v);try{await new Promise((resolve,reject)=>{v.onloadedmetadata=resolve;v.onerror=reject});await v.play();await new Promise(r=>setTimeout(r,1200));return {time:v.currentTime,width:v.videoWidth}}finally{v.pause();v.removeAttribute('src');v.load();v.remove()}},codec.playbackUrl);assert(info.time>0&&info.width===320);assert((await api('frame',codec.handle,.5,0,1)).width===320);await api('closeSource',codec.handle);log('WebM VP8 + Vorbis 内置播放与真实选帧')
 await page.getByRole('textbox',{name:'搜索文件名或路径'}).fill('雾');await until(()=>page.locator('.viewport [role=option]').first().getAttribute('aria-label').then(name=>name?.includes('雾')));await page.locator('.viewport [role=option]').first().click();await until(async()=>{const b=await api('bootstrap');return b.settings.lastBrowse?.query.text==='雾'&&b.settings.lastBrowse?.selected.length===1});await application.close();application=null;await launch();await until(()=>page.getByRole('textbox',{name:'搜索文件名或路径'}).inputValue().then(v=>v==='雾'));await until(()=>page.locator('.viewport [aria-selected=true]').count().then(n=>n===1));log('重启恢复目录、搜索上下文及有效选择')
 const state=await api('bootstrap');assert((await api('entry',video.id)).width>0);await api('settings',{cacheGB:2});assert.equal((await api('bootstrap')).settings.cacheGB,2);log('后台元数据探测和缓存上限设置')
}catch(error){results.push({name:'extra regression',passed:false,error:String(error)});console.error(error);if(page)await page.screenshot({path:'test-results/extra-failure.png'}).catch(()=>{});process.exitCode=1}finally{if(application)await application.close();await fs.writeFile('test-results/extra-e2e.json',JSON.stringify({date:new Date().toISOString(),results},null,2))}
